apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::820503377880:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-77H7W13Z844L
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::820503377880:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-19T10:45:02Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "884"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 5c5a4d0c-244d-4167-827f-e25275a173ae
